// Canonical provider declarations shared by the frontend and installed CLI.
//
// types.ts에서 빼냈다(god-file 라쳇). providerManifest.ts는 이 단일 표를
// 그대로 다시 내보내는 deprecated facade다. 타입은 계약이고 이 표는 데이터인데,
// 표가 늘 때마다 계약 파일이 같이 부풀었다. 여기 있는 값은 전부 실제 CLI의
// `--help` 또는 공식 문서로 확인한 사실이어야 한다 — 짐작으로 채운 플래그는
// 사용자의 실행 명령을 조용히 깨뜨린다(2026-08-11 codex forkFlag 사고).
//
// 필드가 켜는 동작을 알고 쓸 것:
//   configEnv        계정 분리(per-process credential overlay)를 **켠다**.
//                    검증된 어댑터가 없으면 넣지 말고 configDirEnv를 쓴다.
//   conversationList 대화 목록 조회 대상에 **넣는다**. 백엔드 어댑터가 필요하다.
//   conversationFork fork 경로를 **연다**. forkFlag는 copy_and_flag일 때만 덧붙는다.
// 나머지(modelFlag·headlessFlag·mcpSetup·configFile·configDirEnv)는 표시 전용이다.

/** @type {Record<import("./provider-catalog.mjs").Provider, import("./provider-catalog.mjs").ProviderSpec>} */
export const PROVIDERS = {
  claude: {
    label: "Claude Code",
    cmd: "claude",
    resumeCmd: "claude --continue",
    resumeId: (id) => `claude --resume ${id}`,
    conversationList: "local_records",
    forkFlag: "--fork-session",
    conversationFork: "copy_and_flag",
    short: "CL",
    skipPermFlag: "--dangerously-skip-permissions",
    configEnv: "CLAUDE_CONFIG_DIR",
    accountUrl: "https://claude.ai/settings/account",
    credentialFiles: [".credentials.json"],
    core: true,
    basic: true,
    workflowDelegate: true,
    structuredChat: true,
    loginCmd: "claude auth login",
    modelFlag: "--model",
    headlessFlag: "-p",
    configFile: "~/.claude/settings.json",
    mcpSetup: "claude mcp add <name> <commandOrUrl> [args...]",
    configDirEnv: "CLAUDE_CONFIG_DIR",
  },
  codex: {
    label: "Codex",
    cmd: "codex",
    resumeCmd: "codex resume --last",
    resumeId: (id) => `codex resume ${id}`,
    conversationList: "local_records",
    // `-C .` makes the fork's managed worktree authoritative and suppresses
    // the interactive saved-cwd/current-cwd choice.
    forkSource: (id) => `codex -C . fork ${id}`,
    conversationFork: "native_fork_generated",
    short: "CX",
    skipPermFlag: "--dangerously-bypass-approvals-and-sandbox",
    loginCmd: "codex login",
    remoteLoginCmd: "codex login --device-auth",
    accountUrl: "https://chatgpt.com/#settings/Account",
    // The launch adapter projects each account as a credential-only overlay:
    // reviewed directories are symlinked, append logs are hard-linked, and
    // SQLite remains under the canonical CODEX_SQLITE_HOME.
    configEnv: "CODEX_HOME",
    accountSharedStateEnv: 'CODEX_SQLITE_HOME="$HOME/.codex"',
    credentialFiles: ["auth.json"],
    core: true,
    basic: true,
    workflowDelegate: true,
    structuredChat: true,
    modelFlag: "--model",
    headlessFlag: "exec",
    configFile: "~/.codex/config.toml",
    configDirEnv: "CODEX_HOME",
  },
  kimi: {
    label: "Kimi Code",
    cmd: "kimi",
    resumeCmd: "kimi --continue",
    resumeId: (id) => `kimi -S ${id}`,
    short: "KM",
    skipPermFlag: "--yolo",
    loginCmd: "kimi login",
    configEnv: "KIMI_CODE_HOME",
    accountUrl: "https://www.kimi.com",
    // 자격증명 파일 위치가 확인되지 않아 복사는 지원하지 않는다.
    credentialFiles: [],
    detectNames: ["kimi", "kimi-code"],
    logo: "kimi",
    core: true,
    basic: true,
    modelFlag: "--model",
    headlessFlag: "-p",
    configFile: "~/.kimi-code/config.toml",
    configDirEnv: "KIMI_CODE_HOME",
  },

  // 아래 provider도 catalog에 노출하되, 이어서/재개/권한 플래그는 확인된 것만
  // 채운다. 모르는 항목은 비워 새 세션으로만 실행한다(없는 플래그를 만들지 않도록).
  gemini: {
    label: "Gemini CLI",
    cmd: "gemini",
    resumeCmd: "gemini --resume latest",
    resumeId: (id) => `gemini --resume ${id}`,
    conversationList: "local_records",
    skipPermFlag: "--approval-mode=yolo",
    accountUrl: "https://aistudio.google.com/apikey",
    credentialFiles: [],
    logo: "gemini",
    modelFlag: "--model",
    headlessFlag: "-p",
    configFile: "~/.gemini/settings.json",
    mcpSetup: "gemini mcp add",
    configDirEnv: "GEMINI_CLI_HOME",
  },
  cursor: {
    label: "Cursor CLI",
    cmd: "cursor-agent",
    resumeCmd: "cursor-agent resume",
    resumeId: (id) => `cursor-agent --resume=${id}`,
    skipPermFlag: "--force",
    loginCmd: "cursor-agent login",
    credentialFiles: [],
    logo: "cursor",

    accountUrl: "https://cursor.com/dashboard/billing",
    modelFlag: "--model",
    headlessFlag: "-p",
    configFile: "~/.cursor/cli-config.json",
    mcpSetup: "cursor-agent mcp login",
    configDirEnv: "CURSOR_CONFIG_DIR",
  },
  copilot: {
    label: "GitHub Copilot CLI",
    cmd: "copilot",
    resumeCmd: "copilot --continue",
    resumeId: (id) => `copilot --resume=${id}`,
    skipPermFlag: "--allow-all",
    loginCmd: "copilot login",
    credentialFiles: [],
    logo: "copilot",
    accountUrl: "https://github.com/settings/copilot",
    modelFlag: "--model",
    headlessFlag: "-p",
    configFile: "~/.copilot/settings.json",
    mcpSetup: "copilot mcp add",
    configDirEnv: "COPILOT_HOME",
  },
  opencode: {
    label: "OpenCode",
    cmd: "opencode",
    structuredChat: true,
    resumeCmd: "opencode --continue",
    resumeId: (id) => `opencode --session ${id}`,
    conversationList: "provider_cli",
    skipPermFlag: "--auto",
    loginCmd: "opencode auth login",
    credentialFiles: [],
    logo: "opencode",
    forkFlag: "--fork",
    accountUrl: "https://opencode.ai/auth",
    modelFlag: "--model",
    headlessFlag: "run",
    configFile: "~/.config/opencode/opencode.json",
    configDirEnv: "OPENCODE_CONFIG_DIR",
  },
  amp: { label: "Amp", cmd: "amp", credentialFiles: [], logo: "amp",
    resumeCmd: "amp last",
    resumeId: (id) => `amp threads continue ${id}`,
    loginCmd: "amp login",
    accountUrl: "https://ampcode.com/settings",
    headlessFlag: "-x",
    configFile: "~/.config/amp/settings.json",
    configDirEnv: "AMP_SETTINGS_FILE",
  },
  // 대화형 세션은 `goose session` — 맨몸 `goose`는 도움말만 찍는다.
  goose: {
    label: "Goose",
    cmd: "goose session",
    detectNames: ["goose"],
    credentialFiles: [],
    logo: "goose",

    resumeCmd: "goose session --resume",
    resumeId: (id) => `goose session --resume --session-id ${id}`,
    forkFlag: "--fork",
    loginCmd: "goose configure",
    modelFlag: "--model",
    headlessFlag: "run",
    configFile: "~/.config/goose/config.yaml",
    mcpSetup: "goose session --with-extension '<command>'",
    configDirEnv: "GOOSE_PATH_ROOT",
  },
  droid: { label: "Droid", cmd: "droid", credentialFiles: [], logo: "droid",
    resumeCmd: "droid --resume",
    resumeId: (id) => `droid --resume ${id}`,
    forkFlag: "--fork",
    skipPermFlag: "--skip-permissions-unsafe",
    accountUrl: "https://app.factory.ai",
    modelFlag: "--model",
    headlessFlag: "exec",
    configFile: "~/.factory/settings.json",
    mcpSetup: "droid mcp add",
  },
  auggie: {
    label: "Auggie",
    cmd: "auggie",
    credentialFiles: [],
    logo: "auggie",

    resumeCmd: "auggie --continue",
    resumeId: (id) => `auggie --resume ${id}`,
    loginCmd: "auggie login",
    modelFlag: "--model",
    headlessFlag: "--print",
    configFile: "~/.augment/settings.json",
    mcpSetup: "auggie mcp add",
  },
  grok: {
    label: "Grok Build",
    cmd: "grok",
    resumeCmd: "grok --continue",
    resumeId: (id) => `grok --resume ${id}`,
    conversationList: "local_records",
    forkId: (sourceId, newId) =>
      `grok --resume ${sourceId} --fork-session --session-id ${newId}`,
    conversationFork: "native_fork",
    skipPermFlag: "--always-approve",
    loginCmd: "grok login",
    credentialFiles: [],
    logo: "grok",
    accountUrl: "https://accounts.x.ai",
    modelFlag: "--model",
    configFile: "~/.grok/config.toml",
    mcpSetup: "grok mcp add",
    configDirEnv: "GROK_HOME",
  },
  hermes: {
    label: "Hermes Agent",
    cmd: "hermes",
    credentialFiles: [],
    logo: "hermes",

    resumeCmd: "hermes --continue",
    resumeId: (id) => `hermes --resume ${id}`,
    skipPermFlag: "--yolo",
    loginCmd: "hermes login",
    accountUrl: "https://portal.nousresearch.com/manage-subscription",
    modelFlag: "--model",
    headlessFlag: "--oneshot",
    configFile: "~/.hermes/config.yaml",
    configDirEnv: "HERMES_HOME",
  },
  "qwen-code": {
    label: "Qwen Code",
    cmd: "qwen",
    credentialFiles: [],
    logo: "qwen-code",
    resumeCmd: "qwen --continue",
    resumeId: (id) => `qwen --resume ${id}`,
    skipPermFlag: "--approval-mode=yolo",
    modelFlag: "--model",
    headlessFlag: "-p",
    configFile: "~/.qwen/settings.json",
    configDirEnv: "QWEN_HOME",
  },
  cline: { label: "Cline", cmd: "cline", credentialFiles: [], logo: "cline",
    resumeId: (id) => `cline --id ${id}`,
    skipPermFlag: "--auto-approve true",
    loginCmd: "cline auth",
    accountUrl: "https://app.cline.bot/dashboard",
    modelFlag: "--model",
    headlessFlag: "--json",
    configFile: "~/.cline/data/settings/global-settings.json",
    mcpSetup: "cline mcp install <name>",
    configDirEnv: "CLINE_DATA_DIR",
  },
  continue: {
    label: "Continue",
    cmd: "cn",
    credentialFiles: [],
    logo: "continue",

    resumeCmd: "cn --resume",
    forkFlag: "--fork",
    skipPermFlag: "--auto",
    modelFlag: "--model",
    headlessFlag: "-p",
    configFile: "~/.continue/config.yaml",
    mcpSetup: "--mcp <slug>",
    configDirEnv: "CONTINUE_GLOBAL_DIR",
  },
  charm: { label: "Charm", cmd: "crush", credentialFiles: [], logo: "charm",
    resumeCmd: "crush --continue",
    resumeId: (id) => `crush --session ${id}`,
    skipPermFlag: "--yolo",
    loginCmd: "crush login",
    accountUrl: "https://hyper.charm.land",
    modelFlag: "--model",
    headlessFlag: "run",
    configFile: "~/.config/crush/crushrc",
    mcpSetup: "~/.config/crush/crushrc",
    configDirEnv: "CRUSH_GLOBAL_CONFIG",
  },
  codebuff: {
    label: "Codebuff",
    cmd: "codebuff",
    credentialFiles: [],
    logo: "codebuff",

    resumeCmd: "codebuff --continue",
    resumeId: (id) => `codebuff --continue ${id}`,
    loginCmd: "codebuff login",
    accountUrl: "https://www.codebuff.com/usage",
    configFile: "~/.config/manicode/settings.json",
    mcpSetup: "~/.agents/mcp.json",
  },
  // npm 패키지는 @kilocode/cli지만 설치되는 실행 파일은 `kilo`.
  kilocode: {
    label: "Kilo Code",
    cmd: "kilo",
    credentialFiles: [],
    logo: "kilocode",
    // `kilocode`와 `kilo`는 같은 바이너리(@kilocode/cli/bin/kilo)다. 조사 결과는
    // `kilocode ...`로 왔지만 이 매니페스트의 실행 파일은 `kilo`이므로,
    // `kilo --help`로 직접 확인한 형태로 적는다.
    resumeCmd: "kilo --continue",
    resumeId: (id) => `kilo --session ${id}`,
    forkFlag: "--fork",
    loginCmd: "kilo auth",
    skipPermFlag: "--dangerously-skip-permissions",
    accountUrl: "https://app.kilo.ai/profile",
    modelFlag: "--model",
    headlessFlag: "kilo run",
    configFile: "~/.config/kilo/kilo.json",
    mcpSetup: "kilo mcp add",
    configDirEnv: "KILO_CONFIG_DIR",
  },
  kiro: {
    label: "Kiro",
    cmd: "kiro-cli",
    detectNames: ["kiro", "kiro-cli"],
    credentialFiles: [],
    logo: "kiro",

    resumeCmd: "kiro-cli chat --resume",
    resumeId: (id) => `kiro-cli chat --resume-id ${id}`,
    skipPermFlag: "--trust-all-tools",
    loginCmd: "kiro-cli login",
    accountUrl: "https://app.kiro.dev",
    modelFlag: "--model",
    headlessFlag: "--no-interactive",
    configFile: "~/.kiro/settings/cli.json",
    mcpSetup: "kiro-cli mcp add",
  },
  // Atlassian CLI의 서브커맨드로 뜬다 — 프로세스 이름은 `acli`.
  "rovo-dev": {
    label: "Rovo Dev",
    cmd: "acli rovodev run",
    detectNames: ["acli"],
    credentialFiles: [],
    logo: "rovo-dev",
  },
  "mistral-vibe": {
    label: "Mistral Vibe",
    cmd: "vibe",
    detectNames: ["vibe", "vibe-acp"],
    credentialFiles: [],
    logo: "mistral-vibe",
  },
  antigravity: {
    // 설치 스크립트가 까는 실행 파일은 `agy`다(`antigravity` 바이너리는 없다).
    // cmd는 설치 감지(command -v)와 프로세스 감지의 키이기도 하다.
    label: "Antigravity",
    cmd: "agy",
    credentialFiles: [],
    logo: "antigravity",
    resumeCmd: "agy --continue",
    resumeId: (id) => `agy --conversation ${id}`,
    skipPermFlag: "--dangerously-skip-permissions",
    modelFlag: "--model",
    headlessFlag: "-p",
    configFile: "~/.gemini/antigravity-cli/settings.json",
    mcpSetup: "~/.gemini/config/mcp_config.json",
  },
  openclaude: {
    label: "OpenClaude",
    cmd: "openclaude",
    credentialFiles: [],
    logo: "openclaude",

    resumeCmd: "openclaude --continue",
    resumeId: (id) => `openclaude --resume ${id}`,
    forkFlag: "--fork-session",
    skipPermFlag: "--dangerously-skip-permissions",
    loginCmd: "openclaude auth login",
    modelFlag: "--model",
    headlessFlag: "-p",
    configFile: "~/.openclaude.json",
    configDirEnv: "OPENCLAUDE_CONFIG_DIR",
  },
  pi: {
    label: "Pi",
    structuredChat: true,
    cmd: "pi",
    resumeCmd: "pi --continue",
    resumeId: (id) => `pi --session ${id}`,
    conversationList: "local_records",
    forkId: (sourceId, newId) => `pi --fork ${sourceId} --session-id ${newId}`,
    conversationFork: "native_fork",
    credentialFiles: [],
    logo: "pi",
    modelFlag: "--model",
    headlessFlag: "-p",
    configFile: "~/.pi/agent/settings.json",
    configDirEnv: "PI_CODING_AGENT_DIR",
  },
  "oh-my-pi": {
    label: "Oh My Pi",
    cmd: "omp",
    credentialFiles: [],
    logo: "oh-my-pi",
  },
  // npm 패키지는 command-code지만 실행은 `cmd`.
  "command-code": {
    label: "Command Code",
    cmd: "cmd",
    detectNames: ["cmd", "command-code"],
    credentialFiles: [],
    logo: "command-code",
    installationProbeRequiresReady: true,
  },
};

export const PROVIDER_IDS = /** @type {import("./provider-catalog.mjs").Provider[]} */ (Object.keys(PROVIDERS));
