// 자동 생성 파일 — 편집 금지. 갱신: node scripts/themes/convert-schemes.mjs
// upstream: mbadolato/iTerm2-Color-Schemes@171945cb5f1f (MIT) — 출처·라이선스는
// scripts/themes/manifest.json, scripts/themes/UPSTREAM-LICENSE 참조.
import type { ThemeDefinition } from "./themeDefinition";

export const BUNDLED_THEMES: ThemeDefinition[] = [
  {
    "id": "ayu-mirage",
    "name": "Ayu Mirage",
    "appearance": "dark",
    "terminal": {
      "background": "#1f2430",
      "foreground": "#cccac2",
      "cursor": "#ffcc66",
      "selectionBackground": "#306298",
      "black": "#171b24",
      "red": "#ed8274",
      "green": "#87d96c",
      "yellow": "#facc6e",
      "blue": "#6dcbfa",
      "magenta": "#dabafa",
      "cyan": "#90e1c6",
      "white": "#c7c7c7",
      "brightBlack": "#686868",
      "brightRed": "#f28779",
      "brightGreen": "#d5ff80",
      "brightYellow": "#ffd173",
      "brightBlue": "#73d0ff",
      "brightMagenta": "#dfbfff",
      "brightCyan": "#95e6cb",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "catppuccin-macchiato",
    "name": "Catppuccin Macchiato",
    "appearance": "dark",
    "terminal": {
      "background": "#24273a",
      "foreground": "#cad3f5",
      "cursor": "#f4dbd6",
      "selectionBackground": "#8c8188",
      "black": "#494d64",
      "red": "#ed8796",
      "green": "#a6da95",
      "yellow": "#eed49f",
      "blue": "#8aadf4",
      "magenta": "#f5bde6",
      "cyan": "#8bd5ca",
      "white": "#b8c0e0",
      "brightBlack": "#5b6078",
      "brightRed": "#f2a7b2",
      "brightGreen": "#bde3b0",
      "brightYellow": "#f4e3c1",
      "brightBlue": "#adc5f7",
      "brightMagenta": "#f493da",
      "brightCyan": "#a5ded6",
      "brightWhite": "#a5adcb"
    }
  },
  {
    "id": "catppuccin-mocha",
    "name": "Catppuccin Mocha",
    "appearance": "dark",
    "terminal": {
      "background": "#1e1e2e",
      "foreground": "#cdd6f4",
      "cursor": "#f5e0dc",
      "selectionBackground": "#8a7f85",
      "black": "#45475a",
      "red": "#f38ba8",
      "green": "#a6e3a1",
      "yellow": "#f9e2af",
      "blue": "#89b4fa",
      "magenta": "#f5c2e7",
      "cyan": "#94e2d5",
      "white": "#bac2de",
      "brightBlack": "#585b70",
      "brightRed": "#f7aec2",
      "brightGreen": "#c2ecbf",
      "brightYellow": "#fcd682",
      "brightBlue": "#aeccfc",
      "brightMagenta": "#f398da",
      "brightCyan": "#b1eae1",
      "brightWhite": "#a6adc8"
    }
  },
  {
    "id": "cobalt2",
    "name": "Cobalt2",
    "appearance": "dark",
    "terminal": {
      "background": "#132738",
      "foreground": "#ffffff",
      "cursor": "#f0cc09",
      "selectionBackground": "#162e44",
      "black": "#000000",
      "red": "#ff0000",
      "green": "#38de21",
      "yellow": "#ffe50a",
      "blue": "#1460d2",
      "magenta": "#ff005d",
      "cyan": "#00bbbb",
      "white": "#bbbbbb",
      "brightBlack": "#555555",
      "brightRed": "#f40e17",
      "brightGreen": "#3bd01d",
      "brightYellow": "#edc809",
      "brightBlue": "#5555ff",
      "brightMagenta": "#ff55ff",
      "brightCyan": "#6ae3fa",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "dracula",
    "name": "Dracula",
    "appearance": "dark",
    "terminal": {
      "background": "#282a36",
      "foreground": "#f8f8f2",
      "cursor": "#f8f8f2",
      "selectionBackground": "#363948",
      "black": "#21222c",
      "red": "#ff5555",
      "green": "#50fa7b",
      "yellow": "#f1fa8c",
      "blue": "#bd93f9",
      "magenta": "#ff79c6",
      "cyan": "#8be9fd",
      "white": "#f8f8f2",
      "brightBlack": "#6272a4",
      "brightRed": "#ff6e6e",
      "brightGreen": "#69ff94",
      "brightYellow": "#ffffa5",
      "brightBlue": "#d6acff",
      "brightMagenta": "#ff92df",
      "brightCyan": "#a4ffff",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "everforest-dark",
    "name": "Everforest Dark",
    "appearance": "dark",
    "terminal": {
      "background": "#232a2e",
      "foreground": "#d3c6aa",
      "cursor": "#e69875",
      "selectionBackground": "#3c323b",
      "black": "#7a8478",
      "red": "#e67e80",
      "green": "#a7c080",
      "yellow": "#dbbc7f",
      "blue": "#7fbbb3",
      "magenta": "#d699b6",
      "cyan": "#83c092",
      "white": "#f2efdf",
      "brightBlack": "#a6b0a0",
      "brightRed": "#f85552",
      "brightGreen": "#8da101",
      "brightYellow": "#dfa000",
      "brightBlue": "#3a94c5",
      "brightMagenta": "#df69ba",
      "brightCyan": "#35a77c",
      "brightWhite": "#fffbef"
    }
  },
  {
    "id": "flexoki-dark",
    "name": "Flexoki Dark",
    "appearance": "dark",
    "terminal": {
      "background": "#100f0f",
      "foreground": "#cecdc3",
      "cursor": "#cecdc3",
      "selectionBackground": "#282726",
      "black": "#100f0f",
      "red": "#d14d41",
      "green": "#879a39",
      "yellow": "#d0a215",
      "blue": "#4385be",
      "magenta": "#ce5d97",
      "cyan": "#3aa99f",
      "white": "#878580",
      "brightBlack": "#575653",
      "brightRed": "#af3029",
      "brightGreen": "#66800b",
      "brightYellow": "#ad8301",
      "brightBlue": "#205ea6",
      "brightMagenta": "#a02f6f",
      "brightCyan": "#24837b",
      "brightWhite": "#cecdc3"
    }
  },
  {
    "id": "github-dark",
    "name": "GitHub Dark",
    "appearance": "dark",
    "terminal": {
      "background": "#0d1117",
      "foreground": "#e6edf3",
      "cursor": "#2f81f7",
      "selectionBackground": "#7a7f85",
      "black": "#484f58",
      "red": "#ff7b72",
      "green": "#3fb950",
      "yellow": "#d29922",
      "blue": "#58a6ff",
      "magenta": "#bc8cff",
      "cyan": "#39c5cf",
      "white": "#b1bac4",
      "brightBlack": "#6e7681",
      "brightRed": "#ffa198",
      "brightGreen": "#56d364",
      "brightYellow": "#e3b341",
      "brightBlue": "#79c0ff",
      "brightMagenta": "#d2a8ff",
      "brightCyan": "#56d4dd",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "gruvbox-dark",
    "name": "Gruvbox Dark",
    "appearance": "dark",
    "terminal": {
      "background": "#282828",
      "foreground": "#ebdbb2",
      "cursor": "#ebdbb2",
      "selectionBackground": "#47423e",
      "black": "#282828",
      "red": "#cc241d",
      "green": "#98971a",
      "yellow": "#d79921",
      "blue": "#458588",
      "magenta": "#b16286",
      "cyan": "#689d6a",
      "white": "#a89984",
      "brightBlack": "#928374",
      "brightRed": "#fb4934",
      "brightGreen": "#b8bb26",
      "brightYellow": "#fabd2f",
      "brightBlue": "#83a598",
      "brightMagenta": "#d3869b",
      "brightCyan": "#8ec07c",
      "brightWhite": "#ebdbb2"
    }
  },
  {
    "id": "horizon",
    "name": "Horizon",
    "appearance": "dark",
    "terminal": {
      "background": "#1c1e26",
      "foreground": "#d5d8da",
      "cursor": "#6c6f93",
      "selectionBackground": "#44475d",
      "black": "#000000",
      "red": "#e95678",
      "green": "#29d398",
      "yellow": "#fab795",
      "blue": "#26bbd9",
      "magenta": "#ee64ac",
      "cyan": "#59e1e3",
      "white": "#e5e5e5",
      "brightBlack": "#666666",
      "brightRed": "#ec6a88",
      "brightGreen": "#3fdaa4",
      "brightYellow": "#fbc3a7",
      "brightBlue": "#3fc4de",
      "brightMagenta": "#f075b5",
      "brightCyan": "#6be4e6",
      "brightWhite": "#e5e5e5"
    }
  },
  {
    "id": "iceberg-dark",
    "name": "Iceberg Dark",
    "appearance": "dark",
    "terminal": {
      "background": "#161821",
      "foreground": "#c6c8d1",
      "cursor": "#c6c8d1",
      "selectionBackground": "#6e7079",
      "black": "#1e2132",
      "red": "#e27878",
      "green": "#b4be82",
      "yellow": "#e2a478",
      "blue": "#84a0c6",
      "magenta": "#a093c7",
      "cyan": "#89b8c2",
      "white": "#c6c8d1",
      "brightBlack": "#6b7089",
      "brightRed": "#e98989",
      "brightGreen": "#c0ca8e",
      "brightYellow": "#e9b189",
      "brightBlue": "#91acd1",
      "brightMagenta": "#ada0d3",
      "brightCyan": "#95c4ce",
      "brightWhite": "#d2d4de"
    }
  },
  {
    "id": "kanagawa-wave",
    "name": "Kanagawa Wave",
    "appearance": "dark",
    "terminal": {
      "background": "#1f1f28",
      "foreground": "#dcd7ba",
      "cursor": "#dcd7ba",
      "selectionBackground": "#7e7b71",
      "black": "#090618",
      "red": "#c34043",
      "green": "#76946a",
      "yellow": "#c0a36e",
      "blue": "#7e9cd8",
      "magenta": "#957fb8",
      "cyan": "#6a9589",
      "white": "#c8c093",
      "brightBlack": "#727169",
      "brightRed": "#e82424",
      "brightGreen": "#98bb6c",
      "brightYellow": "#e6c384",
      "brightBlue": "#7fb4ca",
      "brightMagenta": "#938aa9",
      "brightCyan": "#7aa89f",
      "brightWhite": "#dcd7ba"
    }
  },
  {
    "id": "monokai",
    "name": "Monokai",
    "appearance": "dark",
    "terminal": {
      "background": "#0c0c0c",
      "foreground": "#d9d9d9",
      "cursor": "#fc971f",
      "selectionBackground": "#202020",
      "black": "#1a1a1a",
      "red": "#f4005f",
      "green": "#98e024",
      "yellow": "#fd971f",
      "blue": "#9d65ff",
      "magenta": "#f4005f",
      "cyan": "#58d1eb",
      "white": "#c4c5b5",
      "brightBlack": "#625e4c",
      "brightRed": "#f4005f",
      "brightGreen": "#98e024",
      "brightYellow": "#e0d561",
      "brightBlue": "#9d65ff",
      "brightMagenta": "#f4005f",
      "brightCyan": "#58d1eb",
      "brightWhite": "#f6f6ef"
    }
  },
  {
    "id": "night-owl",
    "name": "Night Owl",
    "appearance": "dark",
    "terminal": {
      "background": "#011627",
      "foreground": "#d6deeb",
      "cursor": "#7e57c2",
      "selectionBackground": "#304a5f",
      "black": "#011627",
      "red": "#ef5350",
      "green": "#22da6e",
      "yellow": "#addb67",
      "blue": "#82aaff",
      "magenta": "#c792ea",
      "cyan": "#21c7a8",
      "white": "#ffffff",
      "brightBlack": "#575656",
      "brightRed": "#ef5350",
      "brightGreen": "#22da6e",
      "brightYellow": "#ffeb95",
      "brightBlue": "#82aaff",
      "brightMagenta": "#c792ea",
      "brightCyan": "#7fdbca",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "nord",
    "name": "Nord",
    "appearance": "dark",
    "terminal": {
      "background": "#2e3440",
      "foreground": "#d8dee9",
      "cursor": "#eceff4",
      "selectionBackground": "#8d929a",
      "black": "#3b4252",
      "red": "#bf616a",
      "green": "#a3be8c",
      "yellow": "#ebcb8b",
      "blue": "#81a1c1",
      "magenta": "#b48ead",
      "cyan": "#88c0d0",
      "white": "#e5e9f0",
      "brightBlack": "#596377",
      "brightRed": "#bf616a",
      "brightGreen": "#a3be8c",
      "brightYellow": "#ebcb8b",
      "brightBlue": "#81a1c1",
      "brightMagenta": "#b48ead",
      "brightCyan": "#8fbcbb",
      "brightWhite": "#eceff4"
    }
  },
  {
    "id": "oceanic-next",
    "name": "Oceanic Next",
    "appearance": "dark",
    "terminal": {
      "background": "#162c35",
      "foreground": "#c0c5ce",
      "cursor": "#c0c5ce",
      "selectionBackground": "#33444e",
      "black": "#162c35",
      "red": "#ec5f67",
      "green": "#99c794",
      "yellow": "#fac863",
      "blue": "#6699cc",
      "magenta": "#c594c5",
      "cyan": "#5fb3b3",
      "white": "#ffffff",
      "brightBlack": "#65737e",
      "brightRed": "#ec5f67",
      "brightGreen": "#99c794",
      "brightYellow": "#fac863",
      "brightBlue": "#6699cc",
      "brightMagenta": "#c594c5",
      "brightCyan": "#5fb3b3",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "one-dark",
    "name": "One Dark",
    "appearance": "dark",
    "terminal": {
      "background": "#21252b",
      "foreground": "#abb2bf",
      "cursor": "#abb2bf",
      "selectionBackground": "#2a2f38",
      "black": "#21252b",
      "red": "#e06c75",
      "green": "#98c379",
      "yellow": "#e5c07b",
      "blue": "#61afef",
      "magenta": "#c678dd",
      "cyan": "#56b6c2",
      "white": "#abb2bf",
      "brightBlack": "#767676",
      "brightRed": "#e06c75",
      "brightGreen": "#98c379",
      "brightYellow": "#e5c07b",
      "brightBlue": "#61afef",
      "brightMagenta": "#c678dd",
      "brightCyan": "#56b6c2",
      "brightWhite": "#abb2bf"
    }
  },
  {
    "id": "one-half-dark",
    "name": "One Half Dark",
    "appearance": "dark",
    "terminal": {
      "background": "#282c34",
      "foreground": "#dcdfe4",
      "cursor": "#a3b3cc",
      "selectionBackground": "#383d49",
      "black": "#282c34",
      "red": "#e06c75",
      "green": "#98c379",
      "yellow": "#e5c07b",
      "blue": "#61afef",
      "magenta": "#c678dd",
      "cyan": "#56b6c2",
      "white": "#dcdfe4",
      "brightBlack": "#5d677a",
      "brightRed": "#e06c75",
      "brightGreen": "#98c379",
      "brightYellow": "#e5c07b",
      "brightBlue": "#61afef",
      "brightMagenta": "#c678dd",
      "brightCyan": "#56b6c2",
      "brightWhite": "#dcdfe4"
    }
  },
  {
    "id": "rose-pine",
    "name": "Rosé Pine",
    "appearance": "dark",
    "terminal": {
      "background": "#191724",
      "foreground": "#e0def4",
      "cursor": "#e0def4",
      "selectionBackground": "#2d2a3b",
      "black": "#26233a",
      "red": "#eb6f92",
      "green": "#31748f",
      "yellow": "#f6c177",
      "blue": "#9ccfd8",
      "magenta": "#c4a7e7",
      "cyan": "#ebbcba",
      "white": "#e0def4",
      "brightBlack": "#6e6a86",
      "brightRed": "#eb6f92",
      "brightGreen": "#31748f",
      "brightYellow": "#f6c177",
      "brightBlue": "#9ccfd8",
      "brightMagenta": "#c4a7e7",
      "brightCyan": "#ebbcba",
      "brightWhite": "#e0def4"
    }
  },
  {
    "id": "solarized-dark",
    "name": "Solarized Dark",
    "appearance": "dark",
    "terminal": {
      "background": "#002b36",
      "foreground": "#839496",
      "cursor": "#839496",
      "selectionBackground": "#04313c",
      "black": "#073642",
      "red": "#dc322f",
      "green": "#859900",
      "yellow": "#b58900",
      "blue": "#268bd2",
      "magenta": "#d33682",
      "cyan": "#2aa198",
      "white": "#eee8d5",
      "brightBlack": "#335e69",
      "brightRed": "#cb4b16",
      "brightGreen": "#586e75",
      "brightYellow": "#657b83",
      "brightBlue": "#839496",
      "brightMagenta": "#6c71c4",
      "brightCyan": "#93a1a1",
      "brightWhite": "#fdf6e3"
    }
  },
  {
    "id": "synthwave-84",
    "name": "SynthWave '84",
    "appearance": "dark",
    "terminal": {
      "background": "#2a2139",
      "foreground": "#f0eff1",
      "cursor": "#72f1b8",
      "selectionBackground": "#211b2d",
      "black": "#fefefe",
      "red": "#f97e72",
      "green": "#72f1b8",
      "yellow": "#fede5d",
      "blue": "#6d77b3",
      "magenta": "#c792ea",
      "cyan": "#f772e0",
      "white": "#fefefe",
      "brightBlack": "#fefefe",
      "brightRed": "#f88414",
      "brightGreen": "#72f1b8",
      "brightYellow": "#fff951",
      "brightBlue": "#36f9f6",
      "brightMagenta": "#e1acff",
      "brightCyan": "#f92aad",
      "brightWhite": "#fefefe"
    }
  },
  {
    "id": "tokyo-night",
    "name": "Tokyo Night",
    "appearance": "dark",
    "terminal": {
      "background": "#1a1b26",
      "foreground": "#c0caf5",
      "cursor": "#c0caf5",
      "selectionBackground": "#273151",
      "black": "#15161e",
      "red": "#f7768e",
      "green": "#9ece6a",
      "yellow": "#e0af68",
      "blue": "#7aa2f7",
      "magenta": "#bb9af7",
      "cyan": "#7dcfff",
      "white": "#a9b1d6",
      "brightBlack": "#414868",
      "brightRed": "#f7768e",
      "brightGreen": "#9ece6a",
      "brightYellow": "#e0af68",
      "brightBlue": "#7aa2f7",
      "brightMagenta": "#bb9af7",
      "brightCyan": "#7dcfff",
      "brightWhite": "#c0caf5"
    }
  },
  {
    "id": "tokyo-night-storm",
    "name": "Tokyo Night Storm",
    "appearance": "dark",
    "terminal": {
      "background": "#24283b",
      "foreground": "#c0caf5",
      "cursor": "#c0caf5",
      "selectionBackground": "#2d395f",
      "black": "#1d202f",
      "red": "#f7768e",
      "green": "#9ece6a",
      "yellow": "#e0af68",
      "blue": "#7aa2f7",
      "magenta": "#bb9af7",
      "cyan": "#7dcfff",
      "white": "#a9b1d6",
      "brightBlack": "#4e5575",
      "brightRed": "#f7768e",
      "brightGreen": "#9ece6a",
      "brightYellow": "#e0af68",
      "brightBlue": "#7aa2f7",
      "brightMagenta": "#bb9af7",
      "brightCyan": "#7dcfff",
      "brightWhite": "#c0caf5"
    }
  },
  {
    "id": "tomorrow-night",
    "name": "Tomorrow Night",
    "appearance": "dark",
    "terminal": {
      "background": "#1d1f21",
      "foreground": "#c5c8c6",
      "cursor": "#c5c8c6",
      "selectionBackground": "#2a2d31",
      "black": "#000000",
      "red": "#cc6666",
      "green": "#b5bd68",
      "yellow": "#f0c674",
      "blue": "#81a2be",
      "magenta": "#b294bb",
      "cyan": "#8abeb7",
      "white": "#ffffff",
      "brightBlack": "#4c4c4c",
      "brightRed": "#cc6666",
      "brightGreen": "#b5bd68",
      "brightYellow": "#f0c674",
      "brightBlue": "#81a2be",
      "brightMagenta": "#b294bb",
      "brightCyan": "#8abeb7",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "vscode-dark-modern",
    "name": "VS Code Dark Modern",
    "appearance": "dark",
    "terminal": {
      "background": "#1f1f1f",
      "foreground": "#cccccc",
      "cursor": "#ffffff",
      "selectionBackground": "#2d2e30",
      "black": "#272727",
      "red": "#f74949",
      "green": "#2ea043",
      "yellow": "#9e6a03",
      "blue": "#0078d4",
      "magenta": "#d01273",
      "cyan": "#1db4d6",
      "white": "#cccccc",
      "brightBlack": "#5d5d5d",
      "brightRed": "#dc5452",
      "brightGreen": "#23d18b",
      "brightYellow": "#f5f543",
      "brightBlue": "#3b8eea",
      "brightMagenta": "#d670d6",
      "brightCyan": "#29b8db",
      "brightWhite": "#e5e5e5"
    }
  },
  {
    "id": "vscode-dark-plus",
    "name": "VS Code Dark+",
    "appearance": "dark",
    "terminal": {
      "background": "#1e1e1e",
      "foreground": "#cccccc",
      "cursor": "#ffffff",
      "selectionBackground": "#2c2e30",
      "black": "#000000",
      "red": "#cd3131",
      "green": "#0dbc79",
      "yellow": "#e5e510",
      "blue": "#2472c8",
      "magenta": "#bc3fbc",
      "cyan": "#11a8cd",
      "white": "#e5e5e5",
      "brightBlack": "#666666",
      "brightRed": "#f14c4c",
      "brightGreen": "#23d18b",
      "brightYellow": "#f5f543",
      "brightBlue": "#3b8eea",
      "brightMagenta": "#d670d6",
      "brightCyan": "#29b8db",
      "brightWhite": "#e5e5e5"
    }
  },
  {
    "id": "alabaster",
    "name": "Alabaster",
    "appearance": "light",
    "terminal": {
      "background": "#f7f7f7",
      "foreground": "#000000",
      "cursor": "#007acc",
      "selectionBackground": "#dbe9fb",
      "black": "#000000",
      "red": "#aa3731",
      "green": "#448c27",
      "yellow": "#cb9000",
      "blue": "#325cc0",
      "magenta": "#7a3e9d",
      "cyan": "#0083b2",
      "white": "#b7b7b7",
      "brightBlack": "#777777",
      "brightRed": "#f05050",
      "brightGreen": "#60cb00",
      "brightYellow": "#f2af50",
      "brightBlue": "#007acc",
      "brightMagenta": "#e64ce6",
      "brightCyan": "#00aacb",
      "brightWhite": "#f7f7f7"
    }
  },
  {
    "id": "ayu-light",
    "name": "Ayu Light",
    "appearance": "light",
    "terminal": {
      "background": "#f8f9fa",
      "foreground": "#5c6166",
      "cursor": "#ffaa33",
      "selectionBackground": "#7eaae8",
      "black": "#000000",
      "red": "#ea6c6d",
      "green": "#6cbf43",
      "yellow": "#eca944",
      "blue": "#3199e1",
      "magenta": "#9e75c7",
      "cyan": "#46ba94",
      "white": "#bababa",
      "brightBlack": "#686868",
      "brightRed": "#f07171",
      "brightGreen": "#86b300",
      "brightYellow": "#f2ae49",
      "brightBlue": "#399ee6",
      "brightMagenta": "#a37acc",
      "brightCyan": "#4cbf99",
      "brightWhite": "#d1d1d1"
    }
  },
  {
    "id": "catppuccin-latte",
    "name": "Catppuccin Latte",
    "appearance": "light",
    "terminal": {
      "background": "#eff1f5",
      "foreground": "#4c4f69",
      "cursor": "#dc8a78",
      "selectionBackground": "#e6beb7",
      "black": "#bcc0cc",
      "red": "#d20f39",
      "green": "#40a02b",
      "yellow": "#df8e1d",
      "blue": "#1e66f5",
      "magenta": "#ea76cb",
      "cyan": "#179299",
      "white": "#5c5f77",
      "brightBlack": "#acb0be",
      "brightRed": "#e7103f",
      "brightGreen": "#46b02f",
      "brightYellow": "#e49931",
      "brightBlue": "#3878f6",
      "brightMagenta": "#ef95d7",
      "brightCyan": "#19a1a8",
      "brightWhite": "#6c6f85"
    }
  },
  {
    "id": "everforest-light",
    "name": "Everforest Light",
    "appearance": "light",
    "terminal": {
      "background": "#efebd4",
      "foreground": "#5c6a72",
      "cursor": "#f57d26",
      "selectionBackground": "#edecce",
      "black": "#7a8478",
      "red": "#e67e80",
      "green": "#9ab373",
      "yellow": "#c1a266",
      "blue": "#7fbbb3",
      "magenta": "#d699b6",
      "cyan": "#83c092",
      "white": "#b2af9f",
      "brightBlack": "#a6b0a0",
      "brightRed": "#f85552",
      "brightGreen": "#8da101",
      "brightYellow": "#dfa000",
      "brightBlue": "#3a94c5",
      "brightMagenta": "#df69ba",
      "brightCyan": "#35a77c",
      "brightWhite": "#fffbef"
    }
  },
  {
    "id": "flexoki-light",
    "name": "Flexoki Light",
    "appearance": "light",
    "terminal": {
      "background": "#fffcf0",
      "foreground": "#100f0f",
      "cursor": "#100f0f",
      "selectionBackground": "#e7e5da",
      "black": "#100f0f",
      "red": "#af3029",
      "green": "#66800b",
      "yellow": "#ad8301",
      "blue": "#205ea6",
      "magenta": "#a02f6f",
      "cyan": "#24837b",
      "white": "#6f6e69",
      "brightBlack": "#b7b5ac",
      "brightRed": "#d14d41",
      "brightGreen": "#879a39",
      "brightYellow": "#d0a215",
      "brightBlue": "#4385be",
      "brightMagenta": "#ce5d97",
      "brightCyan": "#3aa99f",
      "brightWhite": "#cecdc3"
    }
  },
  {
    "id": "github-light",
    "name": "GitHub Light",
    "appearance": "light",
    "terminal": {
      "background": "#ffffff",
      "foreground": "#1f2328",
      "cursor": "#0969da",
      "selectionBackground": "#8f9194",
      "black": "#24292f",
      "red": "#cf222e",
      "green": "#116329",
      "yellow": "#4d2d00",
      "blue": "#0969da",
      "magenta": "#8250df",
      "cyan": "#1b7c83",
      "white": "#6e7781",
      "brightBlack": "#57606a",
      "brightRed": "#a40e26",
      "brightGreen": "#1a7f37",
      "brightYellow": "#633c01",
      "brightBlue": "#218bff",
      "brightMagenta": "#a475f9",
      "brightCyan": "#3192aa",
      "brightWhite": "#8c959f"
    }
  },
  {
    "id": "gruvbox-light",
    "name": "Gruvbox Light",
    "appearance": "light",
    "terminal": {
      "background": "#fbf1c7",
      "foreground": "#3c3836",
      "cursor": "#3c3836",
      "selectionBackground": "#9c957f",
      "black": "#fbf1c7",
      "red": "#cc241d",
      "green": "#98971a",
      "yellow": "#d79921",
      "blue": "#458588",
      "magenta": "#b16286",
      "cyan": "#689d6a",
      "white": "#7c6f64",
      "brightBlack": "#928374",
      "brightRed": "#9d0006",
      "brightGreen": "#79740e",
      "brightYellow": "#b57614",
      "brightBlue": "#076678",
      "brightMagenta": "#8f3f71",
      "brightCyan": "#427b58",
      "brightWhite": "#3c3836"
    }
  },
  {
    "id": "iceberg-light",
    "name": "Iceberg Light",
    "appearance": "light",
    "terminal": {
      "background": "#e8e9ec",
      "foreground": "#33374c",
      "cursor": "#33374c",
      "selectionBackground": "#8e909c",
      "black": "#dcdfe7",
      "red": "#cc517a",
      "green": "#668e3d",
      "yellow": "#c57339",
      "blue": "#2d539e",
      "magenta": "#7759b4",
      "cyan": "#3f83a6",
      "white": "#33374c",
      "brightBlack": "#8389a3",
      "brightRed": "#cc3768",
      "brightGreen": "#598030",
      "brightYellow": "#b6662d",
      "brightBlue": "#22478e",
      "brightMagenta": "#6845ad",
      "brightCyan": "#327698",
      "brightWhite": "#262a3f"
    }
  },
  {
    "id": "one-half-light",
    "name": "One Half Light",
    "appearance": "light",
    "terminal": {
      "background": "#fafafa",
      "foreground": "#383a42",
      "cursor": "#a5b4e5",
      "selectionBackground": "#dde4fd",
      "black": "#383a42",
      "red": "#e45649",
      "green": "#50a14f",
      "yellow": "#c18401",
      "blue": "#0184bc",
      "magenta": "#a626a4",
      "cyan": "#0997b3",
      "white": "#bababa",
      "brightBlack": "#4f525e",
      "brightRed": "#e06c75",
      "brightGreen": "#98c379",
      "brightYellow": "#d8b36e",
      "brightBlue": "#61afef",
      "brightMagenta": "#c678dd",
      "brightCyan": "#56b6c2",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "one-light",
    "name": "One Light",
    "appearance": "light",
    "terminal": {
      "background": "#f9f9f9",
      "foreground": "#2a2c33",
      "cursor": "#bbbbbb",
      "selectionBackground": "#f3f3f3",
      "black": "#000000",
      "red": "#de3e35",
      "green": "#3f953a",
      "yellow": "#d2b67c",
      "blue": "#2f5af3",
      "magenta": "#950095",
      "cyan": "#3f953a",
      "white": "#bbbbbb",
      "brightBlack": "#000000",
      "brightRed": "#de3e35",
      "brightGreen": "#3f953a",
      "brightYellow": "#d2b67c",
      "brightBlue": "#2f5af3",
      "brightMagenta": "#a00095",
      "brightCyan": "#3f953a",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "rose-pine-dawn",
    "name": "Rosé Pine Dawn",
    "appearance": "light",
    "terminal": {
      "background": "#faf4ed",
      "foreground": "#575279",
      "cursor": "#575279",
      "selectionBackground": "#ede7e3",
      "black": "#f2e9e1",
      "red": "#b4637a",
      "green": "#286983",
      "yellow": "#ea9d34",
      "blue": "#56949f",
      "magenta": "#907aa9",
      "cyan": "#d7827e",
      "white": "#575279",
      "brightBlack": "#9893a5",
      "brightRed": "#b4637a",
      "brightGreen": "#286983",
      "brightYellow": "#ea9d34",
      "brightBlue": "#56949f",
      "brightMagenta": "#907aa9",
      "brightCyan": "#d7827e",
      "brightWhite": "#575279"
    }
  },
  {
    "id": "solarized-light",
    "name": "Solarized Light",
    "appearance": "light",
    "terminal": {
      "background": "#fdf6e3",
      "foreground": "#657b83",
      "cursor": "#657b83",
      "selectionBackground": "#f6efdc",
      "black": "#073642",
      "red": "#dc322f",
      "green": "#859900",
      "yellow": "#b58900",
      "blue": "#268bd2",
      "magenta": "#d33682",
      "cyan": "#2aa198",
      "white": "#bbb5a2",
      "brightBlack": "#002b36",
      "brightRed": "#cb4b16",
      "brightGreen": "#586e75",
      "brightYellow": "#657b83",
      "brightBlue": "#839496",
      "brightMagenta": "#6c71c4",
      "brightCyan": "#93a1a1",
      "brightWhite": "#fdf6e3"
    }
  },
  {
    "id": "tokyo-night-day",
    "name": "Tokyo Night Day",
    "appearance": "light",
    "terminal": {
      "background": "#e1e2e7",
      "foreground": "#3760bf",
      "cursor": "#3760bf",
      "selectionBackground": "#bdc5e3",
      "black": "#e9e9ed",
      "red": "#f52a65",
      "green": "#587539",
      "yellow": "#8c6c3e",
      "blue": "#2e7de9",
      "magenta": "#9854f1",
      "cyan": "#007197",
      "white": "#6172b0",
      "brightBlack": "#a1a6c5",
      "brightRed": "#f52a65",
      "brightGreen": "#587539",
      "brightYellow": "#8c6c3e",
      "brightBlue": "#2e7de9",
      "brightMagenta": "#9854f1",
      "brightCyan": "#007197",
      "brightWhite": "#3760bf"
    }
  },
  {
    "id": "tomorrow",
    "name": "Tomorrow",
    "appearance": "light",
    "terminal": {
      "background": "#ffffff",
      "foreground": "#4d4d4c",
      "cursor": "#4d4d4c",
      "selectionBackground": "#ebebeb",
      "black": "#000000",
      "red": "#c82829",
      "green": "#718c00",
      "yellow": "#eab700",
      "blue": "#4271ae",
      "magenta": "#8959a8",
      "cyan": "#3e999f",
      "white": "#bfbfbf",
      "brightBlack": "#000000",
      "brightRed": "#c82829",
      "brightGreen": "#718c00",
      "brightYellow": "#eab700",
      "brightBlue": "#4271ae",
      "brightMagenta": "#8959a8",
      "brightCyan": "#3e999f",
      "brightWhite": "#ffffff"
    }
  }
];
