//! Asking a box to start a session, over the same channel the phone lists on.
//!
//! # Why this exists
//!
//! Until now the phone could only start work through a paired laptop: the hub
//! takes a "start an agent" request and the laptop does it. That makes starting
//! anything depend on the laptop being awake, which is an availability property
//! and not a security one — the phone reaches the SSH box on its own the rest
//! of the time.
//!
//! The gateway refuses creation through a `command="…",restrict` key by
//! default, because starting a process is a larger authority than attaching to
//! one that already runs. An operator who wants this widens it per box, in the
//! `authorized_keys` line:
//!
//! ```text
//! hmux pair --forced-command '"$HOME/.local/bin/hmux" mobile-gateway --allow-create'
//! ```
//!
//! A box that was not widened answers with a refusal that says exactly that,
//! and this phone shows the sentence rather than hiding the button — the same
//! choice the launch offer makes for a folder on another machine.
//!
//! # Why the shapes are written out here
//!
//! The gateway's request and receipt types are private to that binary, so this
//! module mirrors them, exactly as [`crate::catalog`] mirrors the listing. What
//! keeps the two honest is the version field the far end refuses when it is not
//! one it serves.

use std::io::Read;

use serde::Deserialize;

use crate::catalog::{read_exact_or_end, refusal_in, ReadEnd, RemoteSession, LENGTH_PREFIX_BYTES};

/// The request version that starts in the remote account's home.
const GATEWAY_REQUEST_VERSION_HOME: u16 = 1;

/// The request version that carries an explicit working directory.
///
/// Version 1 admits a create with no directory, and the gateway starts it in
/// the account's home. Version 7 names an exact absolute directory.
pub const GATEWAY_REQUEST_VERSION_WORKING_DIRECTORY: u16 = 7;

/// The receipt version this build reads.
///
/// The gateway pins the receipt at 1 deliberately: the listing negotiates its
/// version, this document does not.
pub const SUPPORTED_CREATE_VERSION: u16 = 1;

/// How much of an answer this client will read before refusing.
pub const MAX_CREATE_ANSWER_BYTES: usize = 256 * 1024;

/// What a created session is started with when the phone asks.
///
/// The same two the desktop's remote open carries. They are what turns a bare
/// shell into a place an agent can be promoted from: typing `claude` in the
/// session the phone just made has to become a managed agent, or the phone made
/// a terminal and called it an agent.
const COMMAND_INTERCEPTS: [(&str, &str); 2] = [("claude", "claude"), ("codex", "codex")];

/// A phone screen is not a terminal window. The size is what the far end opens
/// the pty with, and the attach resizes it to the real surface immediately.
const INITIAL_ROWS: u16 = 24;
const INITIAL_COLUMNS: u16 = 80;

/// The framed document that asks a box to start one standalone session.
///
/// `ids` are generated by the caller so a retry can carry the same ones: the
/// gateway echoes `request_id` and `bridge_nonce`, which is how an answer is
/// matched to its question.
#[must_use]
pub fn create_request(ids: &CreateIds, cwd: Option<&str>) -> Vec<u8> {
    let mut request = serde_json::json!({
        "gateway_request_version": if cwd.is_some() {
            GATEWAY_REQUEST_VERSION_WORKING_DIRECTORY
        } else {
            GATEWAY_REQUEST_VERSION_HOME
        },
        "request": {
            "create_standalone": {
                "request_id": ids.request_id,
                "target_session_id": ids.session_id,
                "launch_owner_proof": ids.launch_proof,
                "session_name": ids.session_name,
                "bridge_nonce": ids.bridge_nonce,
                "initial_rows": INITIAL_ROWS,
                "initial_columns": INITIAL_COLUMNS,
                "command_intercepts": COMMAND_INTERCEPTS
                    .iter()
                    .map(|(command, provider_id)| {
                        serde_json::json!({ "command": command, "provider_id": provider_id })
                    })
                    .collect::<Vec<_>>(),
            }
        }
    });
    if let Some(cwd) = cwd {
        request["request"]["create_standalone"]["cwd"] = cwd.into();
    }
    let payload = request.to_string();
    let mut framed = Vec::with_capacity(LENGTH_PREFIX_BYTES + payload.len());
    framed.extend_from_slice(
        &u32::try_from(payload.len())
            .expect("bounded identifiers and one path are far below u32::MAX")
            .to_be_bytes(),
    );
    framed.extend_from_slice(payload.as_bytes());
    framed
}

/// The identifiers one create carries.
///
/// Every one of them is generated here rather than taken from the user: the
/// gateway bounds them to ASCII alphanumerics and `._:+-`, and a session name
/// somebody typed on a phone is neither bounded nor ASCII.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CreateIds {
    pub request_id: String,
    pub session_id: String,
    pub launch_proof: String,
    pub session_name: String,
    pub bridge_nonce: String,
}

impl CreateIds {
    /// Builds one set from a single random token.
    ///
    /// One token rather than five: they are matched as a group by the receipt,
    /// and five independent values would let a partial read look like a match.
    #[must_use]
    pub fn from_token(token: &str) -> Self {
        let session_id = format!("standalone_{token}");
        Self {
            request_id: format!("phone_create_{token}"),
            launch_proof: format!("phone_launch_{token}"),
            session_name: format!("phone-{session_id}"),
            bridge_nonce: format!("phone_bridge_{token}"),
            session_id,
        }
    }
}

/// The receipt a gateway answers a create with.
#[derive(Debug, Deserialize)]
pub struct CreateReceipt {
    pub gateway_create_version: u16,
    pub request_id: String,
    pub bridge_nonce: String,
    /// The created session, in the same shape a listing carries. The phone
    /// attaches with exactly this — it holds every fence component.
    pub session: RemoteSession,
}

#[derive(Debug)]
pub enum CreateError {
    /// The box refused. The most likely refusal by far is a key that was not
    /// widened, and its message says which flag turns it on.
    Refused {
        code: String,
        message: String,
    },
    UnsupportedVersion {
        found: u16,
        supported: u16,
    },
    /// The answer is for a different question. Not merely wrong — a receipt
    /// that does not echo this request's ids may belong to another create, and
    /// attaching to whatever it names would open somebody else's session.
    Mismatched,
    Malformed {
        detail: String,
    },
    Io {
        detail: String,
    },
}

impl CreateError {
    /// A stable code the screen branches on, in the same vocabulary the other
    /// relay failures use.
    #[must_use]
    pub fn code(&self) -> &str {
        match self {
            Self::Refused { code, .. } => code,
            Self::UnsupportedVersion { .. } => "create_version_unsupported",
            Self::Mismatched => "create_receipt_mismatched",
            Self::Malformed { .. } => "create_malformed",
            Self::Io { .. } => "create_io_failed",
        }
    }
}

impl std::fmt::Display for CreateError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Refused { message, .. } => write!(formatter, "{message}"),
            Self::UnsupportedVersion { found, supported } => write!(
                formatter,
                "이 상자의 hmux 가 다른 판의 생성 문서를 씁니다(받은 판 {found}, 이 앱은 {supported}) — 상자의 hmux 를 갱신하세요"
            ),
            Self::Mismatched => formatter.write_str("상자가 다른 요청의 답을 보냈습니다"),
            Self::Malformed { detail } => write!(formatter, "생성 응답을 읽지 못했습니다: {detail}"),
            Self::Io { detail } => write!(formatter, "{detail}"),
        }
    }
}

/// Reads the one document a create is answered with, and proves it is ours.
pub fn read_created<R: Read>(
    source: &mut R,
    ids: &CreateIds,
    maximum: usize,
) -> Result<CreateReceipt, CreateError> {
    let payload = read_framed(source, maximum)?;
    if let Some((code, message)) = refusal_in(&payload) {
        return Err(CreateError::Refused { code, message });
    }
    let receipt: CreateReceipt =
        serde_json::from_slice(&payload).map_err(|error| CreateError::Malformed {
            detail: error.to_string(),
        })?;
    if receipt.gateway_create_version != SUPPORTED_CREATE_VERSION {
        return Err(CreateError::UnsupportedVersion {
            found: receipt.gateway_create_version,
            supported: SUPPORTED_CREATE_VERSION,
        });
    }
    if receipt.request_id != ids.request_id || receipt.bridge_nonce != ids.bridge_nonce {
        return Err(CreateError::Mismatched);
    }
    Ok(receipt)
}

fn read_framed<R: Read>(source: &mut R, maximum: usize) -> Result<Vec<u8>, CreateError> {
    let mut prefix = [0_u8; LENGTH_PREFIX_BYTES];
    match read_exact_or_end(source, &mut prefix).map_err(|error| CreateError::Io {
        detail: error.to_string(),
    })? {
        ReadEnd::Filled => {}
        ReadEnd::Ended | ReadEnd::Partial => {
            return Err(CreateError::Malformed {
                detail: "상자가 답하기 전에 연결을 닫았습니다".to_string(),
            });
        }
    }
    let length = u32::from_be_bytes(prefix) as usize;
    if length > maximum {
        return Err(CreateError::Malformed {
            detail: format!("상자가 상한({maximum}바이트)을 넘는 {length}바이트를 예고했습니다"),
        });
    }
    let mut payload = vec![0_u8; length];
    match read_exact_or_end(source, &mut payload).map_err(|error| CreateError::Io {
        detail: error.to_string(),
    })? {
        ReadEnd::Filled => {}
        ReadEnd::Ended | ReadEnd::Partial => {
            return Err(CreateError::Malformed {
                detail: "답이 문서 도중에 끊겼습니다".to_string(),
            });
        }
    }
    Ok(payload)
}

#[cfg(test)]
mod tests;
