use ts_rs::TS;

use crate::{
    AgentAdapterIdV2, AgentAdapterSupportV2, AgentEnvironmentTargetV2, AgentInstallScopeV2,
    AgentIntegrationDescriptorV2, AgentIntegrationEffectOwnershipV2,
    AgentIntegrationEffectReceiptV2, AgentIntegrationIdV2, AgentIntegrationInstallActionV2,
    AgentIntegrationInstallPlanV2, AgentIntegrationInstallReceiptV2,
    AgentIntegrationUninstallActionV2, AgentIntegrationUninstallPlanV2,
    AgentNativeMarketplaceNameV2, AgentNativePluginCliCapabilityV2, AgentNativePluginCliCommandV2,
    AgentNativePluginCliOutputV2, AgentNativePluginCliPlanRequestV2, AgentNativePluginCliPlanV2,
    AgentNativePluginCliProbeV2, AgentNativePluginExecutableV2,
    AgentNativePluginMarketplaceSourceV2, AgentNativePluginNameV2,
    AgentNativePluginRegistrationTargetV2, AgentNativePluginSelectorV2, AgentProfileIdV2,
    AgentProviderContractV1, AgentTargetIdV2, ApiVersionRangeV1, CapabilityDeclarationV1,
    CapabilityIdV1, CompatibilityOutcomeV1, ContractVersionRangeV2, ContributionDescriptorV2,
    ContributionFamilyIdV2, ContributionFamilySupportV2, ContributionIdV2, ExtensionAvailabilityV1,
    ExtensionContractV1, ExtensionDescriptorV1, ExtensionFailureCodeV1, ExtensionIdV1,
    FileViewProviderContractV1, HostCompatibilityV1, IssueTrackerAgentBindingSourceV1,
    IssueTrackerAgentBindingV1, IssueTrackerCountsV1, IssueTrackerIssueDetailV1,
    IssueTrackerIssueIdV1, IssueTrackerIssueSummaryV1, IssueTrackerMutationDeliveryV1,
    IssueTrackerOperationV1, IssueTrackerProviderV1, IssueTrackerQueryResultV1,
    IssueTrackerQueryV1, IssueTrackerRepositoryWrapperV1, IssueTrackerWatchEventV1,
    IssueTrackerWatchSnapshotV1, IssueTrackerWatchStateV1, IssueTrackerWatchSubscriptionV1,
    MissingRequiredCapabilitiesV1, NegotiatedContributionV2, PermissionIdV1, PermissionKindIdV2,
    PermissionRequestV2, PhysicalTargetKeyV2, PluginActivationEventV2, PluginBundledAuthorityIdV2,
    PluginBundledCatalogAuthoritySummaryV2, PluginCatalogSelectionV2,
    PluginCatalogSnapshotSha256V2, PluginCompatibilityOutcomeV2, PluginHostContractV2, PluginIdV2,
    PluginIssueTrackerAgentClaimsSurfaceV1, PluginIssueTrackerAgentClaimsV1,
    PluginIssueTrackerDefaultQueryV1, PluginIssueTrackerQueryTitlesV1, PluginLocalizedTextV1,
    PluginManifestV2, PluginPackageCandidateIdV2, PluginPackageSourceIdV2,
    PluginPermissionContributionPlanV2, PluginPermissionIdentityV2,
    PluginPermissionPlanComparisonV2, PluginPermissionPlanDigestV2, PluginPermissionPlanV2,
    PluginPermissionPolicyDigestV2, PluginPermissionReviewChangeV2, PluginPermissionReviewDiffV2,
    PluginPermissionReviewEntryV2, PluginPermissionReviewFieldV2,
    PluginPermissionReviewProjectionDigestV2, PluginPermissionReviewProjectionV2,
    PluginPermissionReviewSubjectV2, PluginPermissionReviewValueV2, PluginPlacementV2,
    PluginPublisherIdV2, PluginResourcePathV2, PluginSettingChoiceV1, PluginSettingDefinitionV1,
    PluginSettingKeyV1, PluginSettingScopeV1, PluginSettingValueV1, PluginSettingsSchemaV1,
    PluginVersionV2, PluginViewContainerIdV1, PluginViewContainerLocationV1, PluginViewContainerV1,
    PluginViewIconV1, PluginViewIdV1, PluginViewKindV1, PluginViewV1, PluginViewsV1,
    PluginWorkflowContributionV1, PluginWorkspaceIdentityV2, ProviderIdV1,
    RuntimeAdapterContractV1, RuntimeKindIdV1, UnavailableReasonV1, WorkflowKindIdV1,
    WorkspaceToolKindIdV1, WorkspaceToolProviderContractV1,
};

use crate::{
    IssueTrackerAgentTaskBindingV2, IssueTrackerAgentTaskContextV2, IssueTrackerCapabilityIdV2,
    IssueTrackerCommonOperationV2, IssueTrackerConnectionIdV2, IssueTrackerDataAuthorityV2,
    IssueTrackerEntityIdV2, IssueTrackerLifecycleV2, IssueTrackerNamedValueV2,
    IssueTrackerProviderStatusV2, IssueTrackerProviderV2, IssueTrackerQueryResultV2,
    IssueTrackerQueryV2, IssueTrackerScopeIdV2, IssueTrackerSourceV2, IssueTrackerTaskDetailV2,
    IssueTrackerTaskDisplayKeyV2, IssueTrackerTaskIdV2, IssueTrackerTaskRefV2,
    IssueTrackerTaskSummaryV2,
};

pub fn typescript_contracts() -> String {
    let declarations = [
        ExtensionIdV1::decl(),
        CapabilityIdV1::decl(),
        PermissionIdV1::decl(),
        ExtensionFailureCodeV1::decl(),
        ProviderIdV1::decl(),
        RuntimeKindIdV1::decl(),
        WorkspaceToolKindIdV1::decl(),
        ApiVersionRangeV1::decl(),
        optional_fields(
            CapabilityDeclarationV1::decl(),
            &["provided", "required", "optional"],
        ),
        AgentProviderContractV1::decl(),
        RuntimeAdapterContractV1::decl(),
        optional_fields(WorkspaceToolProviderContractV1::decl(), &["languages"]),
        optional_fields(
            FileViewProviderContractV1::decl(),
            &["media_types", "file_extensions"],
        ),
        ExtensionContractV1::decl(),
        optional_fields(
            ExtensionDescriptorV1::decl(),
            &["capabilities", "permissions"],
        ),
        optional_fields(
            HostCompatibilityV1::decl(),
            &[
                "provided_capabilities",
                "required_extension_capabilities",
                "granted_permissions",
            ],
        ),
        ExtensionAvailabilityV1::decl(),
        UnavailableReasonV1::decl(),
        MissingRequiredCapabilitiesV1::decl(),
        optional_fields(
            CompatibilityOutcomeV1::decl(),
            &["enabled_optional_capabilities"],
        ),
        PluginIdV2::decl(),
        PluginPublisherIdV2::decl(),
        PluginVersionV2::decl(),
        PluginResourcePathV2::decl(),
        ContributionIdV2::decl(),
        ContributionFamilyIdV2::decl(),
        PermissionKindIdV2::decl(),
        AgentAdapterIdV2::decl(),
        AgentIntegrationIdV2::decl(),
        AgentProfileIdV2::decl(),
        AgentTargetIdV2::decl(),
        AgentNativePluginNameV2::decl(),
        AgentNativeMarketplaceNameV2::decl(),
        PhysicalTargetKeyV2::decl(),
        ContractVersionRangeV2::decl(),
        PluginPlacementV2::decl(),
        PluginActivationEventV2::decl(),
        ContributionDescriptorV2::decl(),
        AgentInstallScopeV2::decl(),
        AgentNativePluginSelectorV2::decl(),
        AgentNativePluginExecutableV2::decl(),
        AgentNativePluginCliCapabilityV2::decl(),
        AgentNativePluginCliProbeV2::decl(),
        AgentNativePluginMarketplaceSourceV2::decl(),
        AgentNativePluginCliOutputV2::decl(),
        AgentNativePluginRegistrationTargetV2::decl(),
        AgentNativePluginCliCommandV2::decl(),
        AgentNativePluginCliPlanV2::decl(),
        AgentNativePluginCliPlanRequestV2::decl(),
        AgentIntegrationDescriptorV2::decl(),
        optional_fields(PermissionRequestV2::decl(), &["parameters"]),
        optional_fields(
            PluginManifestV2::decl(),
            &[
                "activation",
                "contributions",
                "agent_integrations",
                "permissions",
            ],
        ),
        PluginPackageSourceIdV2::decl(),
        PluginPackageCandidateIdV2::decl(),
        PluginBundledAuthorityIdV2::decl(),
        PluginCatalogSnapshotSha256V2::decl(),
        PluginWorkspaceIdentityV2::decl(),
        PluginPermissionPolicyDigestV2::decl(),
        PluginPermissionPlanDigestV2::decl(),
        PluginBundledCatalogAuthoritySummaryV2::decl(),
        PluginCatalogSelectionV2::decl(),
        PluginPermissionIdentityV2::decl(),
        PluginPermissionContributionPlanV2::decl(),
        PluginPermissionPlanV2::decl(),
        PluginPermissionPlanComparisonV2::decl(),
        PluginPermissionReviewProjectionDigestV2::decl(),
        PluginPermissionReviewSubjectV2::decl(),
        PluginPermissionReviewFieldV2::decl(),
        PluginPermissionReviewValueV2::decl(),
        PluginPermissionReviewEntryV2::decl(),
        PluginPermissionReviewProjectionV2::decl(),
        PluginPermissionReviewChangeV2::decl(),
        PluginPermissionReviewDiffV2::decl(),
        ContributionFamilySupportV2::decl(),
        AgentAdapterSupportV2::decl(),
        optional_fields(
            PluginHostContractV2::decl(),
            &[
                "contribution_families",
                "agent_adapters",
                "permission_kinds",
            ],
        ),
        NegotiatedContributionV2::decl(),
        PluginCompatibilityOutcomeV2::decl(),
        PluginSettingKeyV1::decl(),
        PluginSettingScopeV1::decl(),
        PluginSettingChoiceV1::decl(),
        PluginSettingDefinitionV1::decl(),
        PluginSettingValueV1::decl(),
        optional_fields(PluginSettingsSchemaV1::decl(), &["settings"]),
        PluginViewContainerIdV1::decl(),
        PluginViewIdV1::decl(),
        optional_fields(PluginLocalizedTextV1::decl(), &["translations"]),
        PluginViewContainerLocationV1::decl(),
        PluginViewIconV1::decl(),
        PluginViewContainerV1::decl(),
        PluginIssueTrackerDefaultQueryV1::decl(),
        PluginIssueTrackerAgentClaimsSurfaceV1::decl(),
        PluginIssueTrackerAgentClaimsV1::decl(),
        optional_fields(
            PluginIssueTrackerQueryTitlesV1::decl(),
            &["ready", "list", "human"],
        ),
        optional_fields(PluginViewKindV1::decl(), &["query_titles"]),
        // The view flattens its kind, so the optional field is repeated here.
        optional_fields(PluginViewV1::decl(), &["query_titles"]),
        PluginViewsV1::decl(),
        WorkflowKindIdV1::decl(),
        PluginWorkflowContributionV1::decl(),
        IssueTrackerIssueIdV1::decl(),
        IssueTrackerOperationV1::decl(),
        IssueTrackerAgentBindingSourceV1::decl(),
        IssueTrackerAgentBindingV1::decl(),
        IssueTrackerMutationDeliveryV1::decl(),
        IssueTrackerProviderV1::decl(),
        IssueTrackerQueryV1::decl(),
        IssueTrackerRepositoryWrapperV1::decl(),
        IssueTrackerCountsV1::decl(),
        IssueTrackerIssueSummaryV1::decl(),
        IssueTrackerIssueDetailV1::decl(),
        IssueTrackerQueryResultV1::decl(),
        IssueTrackerWatchSnapshotV1::decl(),
        IssueTrackerWatchStateV1::decl(),
        IssueTrackerWatchEventV1::decl(),
        IssueTrackerWatchSubscriptionV1::decl(),
        IssueTrackerCapabilityIdV2::decl(),
        IssueTrackerConnectionIdV2::decl(),
        IssueTrackerScopeIdV2::decl(),
        IssueTrackerTaskIdV2::decl(),
        IssueTrackerEntityIdV2::decl(),
        IssueTrackerTaskDisplayKeyV2::decl(),
        IssueTrackerCommonOperationV2::decl(),
        IssueTrackerDataAuthorityV2::decl(),
        IssueTrackerProviderV2::decl(),
        IssueTrackerSourceV2::decl(),
        IssueTrackerTaskRefV2::decl(),
        IssueTrackerLifecycleV2::decl(),
        IssueTrackerProviderStatusV2::decl(),
        IssueTrackerNamedValueV2::decl(),
        IssueTrackerTaskSummaryV2::decl(),
        IssueTrackerTaskDetailV2::decl(),
        IssueTrackerAgentTaskBindingV2::decl(),
        IssueTrackerAgentTaskContextV2::decl(),
        IssueTrackerQueryV2::decl(),
        IssueTrackerQueryResultV2::decl(),
        AgentEnvironmentTargetV2::decl(),
        AgentIntegrationInstallActionV2::decl(),
        optional_fields(
            AgentIntegrationInstallPlanV2::decl(),
            &["skipped_optional_integrations"],
        ),
        AgentIntegrationEffectOwnershipV2::decl(),
        AgentIntegrationEffectReceiptV2::decl(),
        AgentIntegrationInstallReceiptV2::decl(),
        AgentIntegrationUninstallActionV2::decl(),
        AgentIntegrationUninstallPlanV2::decl(),
    ]
    .map(normalize_whitespace)
    .map(|declaration| format!("export {declaration}"));
    format!(
        "// @generated by `pnpm contracts:write`; do not edit by hand.\n\
         // Wire DTOs only. Behavior traits remain backend-owned.\n\n{}\n",
        declarations.join("\n\n")
    )
}

fn normalize_whitespace(declaration: String) -> String {
    declaration
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n")
}

fn optional_fields(mut declaration: String, fields: &[&str]) -> String {
    for field in fields {
        let required = format!("{field}: ");
        let optional = format!("{field}?: ");
        assert!(
            declaration.contains(&required),
            "generated declaration is missing expected field {field}"
        );
        declaration = declaration.replacen(&required, &optional, 1);
    }
    declaration
}
