use super::*;
use base64::{Engine, engine::general_purpose::STANDARD};

const KEY: &str = "4b7c85c550a96babf9616bed389578c6866e6cd696c6ce098860123a1d49ec9d";
const PLAIN: &str = r#"{"cookies":[],"origins":[{"origin":"https://example.test","localStorage":[{"name":"한글","value":"값"}]}]}"#;
// Independently generated by Node crypto with the pinned upstream envelope,
// SHA256(UTF8("fixture 암호화 secret")) and nonce 000102030405060708090a0b.
const NODE_VECTOR: &str = "AAECAwQFBgcICQoLe4MmP7Kdo7qtuwF4hj2ZdvQ1HOIR0cPUGxEZdziUuFSxylD5E5E0XhKoXKKTt6593zt76D7v1HaNS4qGQnPXSL+6CNVfZVtgl7p68T18loNfOb7yT8rnbS/5UxHylq+gSTTtPvy5Jcm6puSCvg5PkIrRe2BSADOlyxJaro0=";

#[test]
fn state_cipher_accepts_independent_vector_and_never_reuses_its_nonce() {
    let key = BrowserStateKey::try_from(KEY.to_owned()).unwrap();
    assert_eq!(
        key.decrypt(&STANDARD.decode(NODE_VECTOR).unwrap()).unwrap(),
        PLAIN.as_bytes()
    );
    let one = key.encrypt(PLAIN.as_bytes()).unwrap();
    let two = key.encrypt(PLAIN.as_bytes()).unwrap();
    assert_ne!(one[..12], two[..12]);
    for encrypted in [one, two] {
        assert_eq!(encrypted.len(), PLAIN.len() + 28);
        assert_eq!(key.decrypt(&encrypted).unwrap(), PLAIN.as_bytes());
    }
    assert!(!format!("{key:?}").contains(KEY));
}

#[test]
fn state_cipher_authenticates_nonce_ciphertext_and_tag_before_returning_plaintext() {
    let key = BrowserStateKey::try_from(KEY.to_owned()).unwrap();
    let encrypted = STANDARD.decode(NODE_VECTOR).unwrap();
    for offset in [0, 12, encrypted.len() - 1] {
        let mut tampered = encrypted.clone();
        tampered[offset] ^= 1;
        assert_eq!(
            key.decrypt(&tampered),
            Err("browser_state_decryption_failed")
        );
    }
    let wrong = BrowserStateKey::try_from("00".repeat(32)).unwrap();
    assert_eq!(
        wrong.decrypt(&encrypted),
        Err("browser_state_decryption_failed")
    );
    for length in 0..28 {
        assert_eq!(
            key.decrypt(&encrypted[..length]),
            Err("browser_state_decryption_failed")
        );
    }
    for invalid in [
        "",
        "not a key",
        &"g".repeat(64),
        &"a".repeat(63),
        &"a".repeat(65),
    ] {
        assert!(BrowserStateKey::try_from(invalid.to_owned()).is_err());
    }
}

#[test]
fn state_cipher_accounts_for_envelope_bytes_inside_the_existing_artifact_bound() {
    let key = BrowserStateKey::try_from(KEY.to_owned()).unwrap();
    let oversized = vec![0; super::super::super::capture::MAX_ARTIFACT_BYTES - 27];
    assert_eq!(key.encrypt(&oversized), Err("browser_artifact_too_large"));
}
