import supportedModes from "@/contracts/generated/providerPermissionModes.json";
import { t } from "@/lib/i18n";
import type { DureAgentRunPermissionOverrideV1 } from "@/lib/ipc/dureAgentRun";
import type { DureProviderPermissionModeV1 } from "@/lib/ipc/dureAgentRuntime";

export type LaunchPermissionSelection =
	| "inherit"
	| DureAgentRunPermissionOverrideV1;

const overrides = {
	default: "require_approvals",
	auto_edit: "auto_edit",
	skip_permissions: "bypass_approvals",
} as const;

const modesByProvider = new Map(
	Object.entries(supportedModes) as [
		string,
		readonly DureProviderPermissionModeV1[],
	][],
);

/** Generated by the execution adapter's accepted plans, not UI provider guesses. */
export function providerPermissionOptions(provider: string) {
	const modes = modesByProvider.get(provider) ?? [];
	return modes.map((value) => ({
		value,
		override: overrides[value],
		label: launchPermissionLabel(overrides[value]),
		tone: value === "skip_permissions" ? ("danger" as const) : undefined,
	}));
}

export function launchPermissionLabel(
	permission: LaunchPermissionSelection,
): string {
	switch (permission) {
		case "inherit":
			return t("common.systemDefault");
		case "require_approvals":
			return t("agents.chat.permissionDefault");
		case "auto_edit":
			return t("agents.chat.permissionAutoEdit");
		case "bypass_approvals":
			return t("agents.chat.permissionSkip");
	}
}

export function launchPermissionDescription(
	permission: LaunchPermissionSelection,
): string {
	switch (permission) {
		case "inherit":
			return t("agents.permission.inheritHint");
		case "require_approvals":
			return t("agents.permission.standardHint");
		case "auto_edit":
			return t("agents.permission.autoEditHint");
		case "bypass_approvals":
			return t("agents.permission.bypassHint");
	}
}
