import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, test } from "vitest";
import { withoutLocalGitOverrides } from "./lib/git-environment.mjs";
import {
  RELEASE_CANDIDATE_FILES,
  RELEASE_CARGO_WORKSPACES,
  prepareReleaseCandidate,
} from "./lib/release-candidate.mjs";

const temporaryDirectories = [];
const gitEnvironment = withoutLocalGitOverrides();
const fixtureCargoWorkspaces = [
  {
    lockPath: "src-tauri/Cargo.lock",
    versionedPackages: [
      "dure",
      "hmux-client",
      "hmux-host",
      "hmux-local-platform",
      "hmux-runtime-contract",
      "hmux-session-protocol",
      "hmux-ssh-transport",
      "terminal-state-protocol",
    ],
  },
  {
    lockPath: "hmux/Cargo.lock",
    versionedPackages: [
      "hmux-cli",
      "hmux-client",
      "hmux-host",
      "hmux-local-platform",
      "hmux-release-candidate",
      "hmux-release-trust",
      "hmux-runtime",
      "hmux-runtime-contract",
      "hmux-session-protocol",
      "hmux-ssh-transport",
      "terminal-core-ghostty-proof",
      "terminal-state-protocol",
      "terminal-state-protocol-codegen",
    ],
  },
  {
    lockPath: "crates/dure-app/Cargo.lock",
    versionedPackages: [
      "hmux-client",
      "hmux-host",
      "hmux-local-platform",
      "hmux-runtime-contract",
      "hmux-session-protocol",
      "terminal-state-protocol",
    ],
  },
  {
    lockPath: "mobile/src-tauri/Cargo.lock",
    versionedPackages: [
      "hmux-client",
      "hmux-host",
      "hmux-local-platform",
      "hmux-runtime-contract",
      "hmux-session-protocol",
      "hmux-ssh-transport",
      "terminal-state-protocol",
    ],
  },
];

afterEach(() => {
  while (temporaryDirectories.length > 0) {
    fs.rmSync(temporaryDirectories.pop(), { recursive: true, force: true });
  }
});

function git(cwd, ...args) {
  return execFileSync("git", args, {
    cwd,
    encoding: "utf8",
    env: gitEnvironment,
    stdio: ["ignore", "pipe", "pipe"],
  }).trim();
}

function write(root, file, contents) {
  const target = path.join(root, file);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, contents);
}

function lock(names, version = "1.2.3") {
  return [
    "# This file is automatically @generated by Cargo.",
    "version = 4",
    "",
    ...names.flatMap((name) => [
      "[[package]]",
      `name = "${name}"`,
      `version = "${version}"`,
      "",
    ]),
  ].join("\n");
}

function versionCount(root, file, version) {
  return [
    ...fs
      .readFileSync(path.join(root, file), "utf8")
      .matchAll(new RegExp(`^version = "${version}"$`, "gm")),
  ].length;
}

function fixture() {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "release-candidate-"));
  temporaryDirectories.push(parent);
  const root = path.join(parent, "repository");
  const outputDirectory = path.join(parent, "artifact");
  fs.mkdirSync(root);

  write(root, "package.json", '{\n  "name": "dure",\n  "version": "1.2.3"\n}\n');
  write(root, "cli/package.json", '{\n  "name": "hebbian-cli",\n  "version": "1.2.3"\n}\n');
  write(
    root,
    "src-tauri/tauri.conf.json",
    '{\n  "productName": "Dure",\n  "version": "1.2.3"\n}\n',
  );
  write(
    root,
    "src-tauri/Cargo.toml",
    '[package]\nname = "dure"\nversion = "1.2.3"\n',
  );
  write(
    root,
    "hmux/Cargo.toml",
    '[workspace]\nmembers = []\n\n[workspace.package]\nversion = "1.2.3"\n',
  );
  write(
    root,
    "src-tauri/Cargo.lock",
    lock([
      "dure",
      "hmux-client",
      "hmux-host",
      "hmux-local-platform",
      "hmux-runtime-contract",
      "hmux-session-protocol",
      "hmux-ssh-transport",
      "terminal-state-protocol",
    ]),
  );
  write(
    root,
    "hmux/Cargo.lock",
    lock([
      "hmux-cli",
      "hmux-client",
      "hmux-host",
      "hmux-local-platform",
      "hmux-runtime",
      "hmux-runtime-contract",
      "hmux-session-protocol",
      "hmux-ssh-transport",
      "hmux-release-candidate",
      "hmux-release-trust",
      "terminal-core-ghostty-proof",
      "terminal-state-protocol",
      "terminal-state-protocol-codegen",
    ]),
  );
  write(
    root,
    "crates/dure-app/Cargo.lock",
    lock([
      "hmux-client",
      "hmux-host",
      "hmux-local-platform",
      "hmux-runtime-contract",
      "hmux-session-protocol",
      "terminal-state-protocol",
    ]),
  );
  write(
    root,
    "mobile/src-tauri/Cargo.lock",
    `${lock([
      "hmux-client",
      "hmux-host",
      "hmux-local-platform",
      "hmux-runtime-contract",
      "hmux-session-protocol",
      "hmux-ssh-transport",
      "terminal-state-protocol",
    ])}\n[[package]]\nname = "hebbian-mobile"\nversion = "1.2.3"\n`,
  );

  git(root, "init", "-b", "main");
  git(root, "config", "user.name", "Candidate Test");
  git(root, "config", "user.email", "candidate@example.test");
  git(root, "config", "commit.gpgSign", "false");
  git(root, "add", ".");
  git(root, "commit", "-m", "base");
  return {
    baseSha: git(root, "rev-parse", "HEAD"),
    outputDirectory,
    parent,
    root,
  };
}

function updateFixtureLocks(root, currentVersion, version) {
  const packageBlock =
    /^\[\[package\]\]\n.*?(?=^\[\[package\]\]\n|(?![\s\S]))/gms;
  for (const { lockPath: file, versionedPackages } of fixtureCargoWorkspaces) {
    const target = path.join(root, file);
    const expected = new Set(versionedPackages);
    const seen = new Set();
    const updated = fs.readFileSync(target, "utf8").replace(
      packageBlock,
      (block) => {
        const name = block.match(/^name = "([^"]+)"$/m)?.[1];
        if (!expected.has(name)) return block;
        seen.add(name);
        return block.replace(
          `version = "${currentVersion}"`,
          `version = "${version}"`,
        );
      },
    );
    if (seen.size !== expected.size) {
      throw new Error(`fixture package set mismatch for ${file}`);
    }
    fs.writeFileSync(target, updated);
  }
}

describe("bounded release candidate", () => {
  test("emits an exact-base manifest and patch for only release version files", () => {
    const target = fixture();
    const manifest = prepareReleaseCandidate({
      baseSha: target.baseSha,
      bumpKind: "patch",
      outputDirectory: target.outputDirectory,
      root: target.root,
      updateLocks: updateFixtureLocks,
    });
    const patch = fs.readFileSync(
      path.join(target.outputDirectory, "version.patch"),
    );

    expect(manifest).toEqual({
      schemaVersion: 1,
      baseSha: target.baseSha,
      bump: "patch",
      currentVersion: "1.2.3",
      version: "1.2.4",
      tag: "v1.2.4",
      files: RELEASE_CANDIDATE_FILES,
      patchSha256: createHash("sha256").update(patch).digest("hex"),
    });
    expect(
      JSON.parse(
        fs.readFileSync(
          path.join(target.outputDirectory, "candidate.json"),
          "utf8",
        ),
      ),
    ).toEqual(manifest);
    expect(
      git(target.root, "diff", "--name-only").split("\n").sort(),
    ).toEqual([...RELEASE_CANDIDATE_FILES].sort());
    expect(
      RELEASE_CARGO_WORKSPACES.map(
        ({ manifestPath, lockPath, versionedPackages }) => ({
          manifestPath,
          lockPath,
          versionedPackageCount: versionedPackages.length,
        }),
      ),
    ).toEqual([
      {
        manifestPath: "src-tauri/Cargo.toml",
        lockPath: "src-tauri/Cargo.lock",
        versionedPackageCount: 8,
      },
      {
        manifestPath: "hmux/Cargo.toml",
        lockPath: "hmux/Cargo.lock",
        versionedPackageCount: 13,
      },
      {
        manifestPath: "crates/dure-app/Cargo.toml",
        lockPath: "crates/dure-app/Cargo.lock",
        versionedPackageCount: 6,
      },
      {
        manifestPath: "mobile/src-tauri/Cargo.toml",
        lockPath: "mobile/src-tauri/Cargo.lock",
        versionedPackageCount: 7,
      },
    ]);
    expect(
      RELEASE_CARGO_WORKSPACES.map(({ lockPath }) =>
        versionCount(target.root, lockPath, "1.2.4"),
      ),
    ).toEqual([8, 13, 6, 7]);
    expect(
      fs.readFileSync(
        path.join(target.root, "mobile/src-tauri/Cargo.lock"),
        "utf8",
      ),
    ).toContain('name = "hebbian-mobile"\nversion = "1.2.3"');
  });

  test("rejects an unexpected file produced while preparing the candidate", () => {
    const target = fixture();
    expect(() =>
      prepareReleaseCandidate({
        baseSha: target.baseSha,
        bumpKind: "patch",
        outputDirectory: target.outputDirectory,
        root: target.root,
        updateLocks(root, currentVersion, version) {
          updateFixtureLocks(root, currentVersion, version);
          write(root, "unexpected.txt", "candidate side effect\n");
        },
      }),
    ).toThrow(/release_candidate_files_mismatch/);
    expect(fs.readdirSync(target.outputDirectory)).toEqual([]);
  });

  test("rejects changes to a source-less package outside the version set", () => {
    const target = fixture();
    expect(() =>
      prepareReleaseCandidate({
        baseSha: target.baseSha,
        bumpKind: "patch",
        outputDirectory: target.outputDirectory,
        root: target.root,
        updateLocks(root, currentVersion, version) {
          updateFixtureLocks(root, currentVersion, version);
          const mobileLock = path.join(root, "mobile/src-tauri/Cargo.lock");
          fs.writeFileSync(
            mobileLock,
            fs
              .readFileSync(mobileLock, "utf8")
              .replace(
                `name = "hebbian-mobile"\nversion = "${currentVersion}"`,
                `name = "hebbian-mobile"\nversion = "${version}"`,
              ),
          );
        },
      }),
    ).toThrow(/release_candidate_lock_mismatch: mobile\/src-tauri\/Cargo.lock/);
  });

  test("rejects a dirty or non-exact-base checkout before mutation", () => {
    const dirty = fixture();
    write(dirty.root, "untracked.txt", "dirty\n");
    expect(() =>
      prepareReleaseCandidate({
        baseSha: dirty.baseSha,
        bumpKind: "minor",
        outputDirectory: dirty.outputDirectory,
        root: dirty.root,
        updateLocks: updateFixtureLocks,
      }),
    ).toThrow(/release_candidate_dirty/);

    const wrongBase = fixture();
    expect(() =>
      prepareReleaseCandidate({
        baseSha: "a".repeat(40),
        bumpKind: "minor",
        outputDirectory: wrongBase.outputDirectory,
        root: wrongBase.root,
        updateLocks: updateFixtureLocks,
      }),
    ).toThrow(/release_candidate_base_mismatch/);
  });
});
